### ISSUE TITLE
Top of main is hidden behind header when tall logo is used

### ISSUE THREAD

**Issue by gareththered** [onweru/compose#8]
The default logo is approx 160x35 and the page layout works.  However, if a taller logo is used (160x70) the first line of text (approx h1's worth) becomes hidden behind the now taller header.  This seems to be the case on MS Edge and on Firefox.  I've not tested on others.

I believe a taller header should push the main body down - not overlap it.

**Comment by onweru** [comment]
@gareththered,

I will fix this.

**Comment by onweru** [comment]
@gareththered, this is fixed now.

**Comment by freakinhippie** [comment]
This issue seems to either still exist, or was reintroduced at some point.
